{{- if .Values.persistence.data.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "agentarmor.fullname" . }}-data
  labels:
    {{- include "agentarmor.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.data.accessMode }}
  {{- if .Values.persistence.data.storageClass }}
  storageClassName: {{ .Values.persistence.data.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
{{- end }}
---
{{- if .Values.persistence.certs.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "agentarmor.fullname" . }}-certs
  labels:
    {{- include "agentarmor.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.certs.accessMode }}
  {{- if .Values.persistence.certs.storageClass }}
  storageClassName: {{ .Values.persistence.certs.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.certs.size }}
{{- end }}
